### ISSUE TITLE
Can you please suggest how to plot the output results : 

### ISSUE THREAD

**Issue by meghavarshney** [marcelTBI/GenomeScreen#5]
Need to plot Out put results , as in out put color code is mentioned so how to utilize that in visualization . Like module name or any script which can help

**Comment by marcelTBI** [comment]
Unfortunately, the scripts to plot out results are the company's intellectual property and they are not available to the public. However, they were done as classic matplotlib visualization scripts, so recreating them should not be a tough issue. I do not know of any module/script that does it out of the box with minimal changes to the code (since visualization is usually a very fine-tuned process, and everybody will do it differently).
